### ISSUE TITLE
Garbage

### ISSUE THREAD

**Issue by Zanderthebunny** [ItsLJcool/LJ-Arcade-Mod#2]
I'm Sorry But This YCE Mod Is The Worst Thing I've Ever Laid My Eyes On, Like On God The Code Is Terrible And Just The Concept Its self Sucks, _**Do Better**_

**Comment by ItsLJcool** [comment]
https://github.com/ItsLJcool/LJ-Arcade-Mod/assets/54383469/1590f502-d409-4a21-8095-6dc4c2bc4b4e

**Comment by NovaAshwolfDev** [comment]
![minecraft-mr-bis-tom-nook-dies](https://github.com/ItsLJcool/LJ-Arcade-Mod/assets/61569905/02a9a17a-8194-4d08-b526-330ff036aee8)
